#!/usr/bin/env python3
"""
YouTube Lecture Notes Taker
─────────────────────────────────────────────────────────
OS     : Fedora Linux (Wayland primary, X11 fallback)
Capture: wf-recorder (Wayland) → ffmpeg x11grab (X11 fallback)
AI     : Gemini 2.5 Flash  ← video + audio together → exhaustive lecture notes
Output : Markdown file with full explanations, examples, Q&A per concept

HOW IT WORKS:
  Every CHUNK_MINUTES the script stops the current screen recording,
  uploads the video chunk to Gemini Files API (video + audio in one file),
  and asks Gemini to write detailed notes from what it sees AND hears.
  A new chunk starts immediately so nothing is missed.

USAGE:
  python youtube_notes.py
  → asks for subject + notes folder, then just watch your videos.
  → Ctrl+C at any time to process the final partial chunk and exit.

INSTALL (one-time):
  sudo dnf install wf-recorder ffmpeg    # Fedora
  pip install google-genai --break-system-packages
"""

import os, sys, time, threading, subprocess, signal, uuid, json, argparse
from datetime import datetime

from google import genai

# ══════════════════════════════════════════════════════
#  CLI ARGS — when launched from the UI (server.js), these are
#  provided directly and the script must NOT block on input().
#  When run by hand with no args, it falls back to interactive prompts.
# ══════════════════════════════════════════════════════
_parser = argparse.ArgumentParser()
_parser.add_argument("--subject",   default=None)
_parser.add_argument("--notes-dir", default=None)
_parser.add_argument("--chunk",     default=None, type=int)
_cli_args, _ = _parser.parse_known_args()

# ══════════════════════════════════════════════════════
#  CONFIG
# ══════════════════════════════════════════════════════
_SCRIPT_DIR  = os.path.dirname(os.path.abspath(__file__))
_CONFIG_FILE = os.path.join(_SCRIPT_DIR, "config.json")

def _load_config() -> dict:
    if os.path.exists(_CONFIG_FILE):
        with open(_CONFIG_FILE, "r") as f:
            return json.load(f)
    return {}

_CFG = _load_config()

# Multiple keys can come from the GEMINI_KEYS env var (comma-separated, set
# by server.js from the UI's key list) or directly from config.json when
# run standalone. Falls back to the old single "gemini_key" field too.
_env_keys = [k.strip() for k in os.environ.get("GEMINI_KEYS", "").split(",") if k.strip()]
_cfg_keys = [k for k in _CFG.get("gemini_keys", []) if k]
GEMINI_API_KEYS = _env_keys or _cfg_keys or ([_CFG["gemini_key"]] if _CFG.get("gemini_key") and _CFG["gemini_key"] != "YOUR_GEMINI_KEY" else [])

if _env_keys:
    print(f"🔑 {len(_env_keys)} Gemini key(s) loaded from GEMINI_KEYS env var", flush=True)
elif GEMINI_API_KEYS:
    print(f"🔑 {len(GEMINI_API_KEYS)} Gemini key(s) loaded from {_CONFIG_FILE}", flush=True)
else:
    print("❌ No Gemini API key found (checked env var GEMINI_KEYS and config.json)", flush=True)

# Chunk length in minutes — how often Gemini generates notes
# 10 min is a good balance: small enough to catch each topic, large enough for context
CHUNK_MINUTES = 10

# Video recording quality — lower CRF = better quality but larger file
# 28 = good quality, ~50-150 MB per 10-min chunk (safe for Gemini Files API)
VIDEO_CRF = 28
VIDEO_FPS = 10   # 10 fps is plenty for lecture content, keeps files small

# ══════════════════════════════════════════════════════
#  NOTES FILE SETUP  (called after subject is known)
# ══════════════════════════════════════════════════════
NOTES_FILE = None
FILE_LOCK  = threading.Lock()

def init_notes_file(subject: str, notes_dir: str) -> str:
    os.makedirs(notes_dir, exist_ok=True)
    date_str   = datetime.now().strftime("%Y-%m-%d")
    subject_clean = subject.replace(" ", "_")
    path = os.path.join(notes_dir, f"{subject_clean}_Notes_{date_str}.md")
    with open(path, "w", encoding="utf-8") as f:
        f.write(f"# 📐 {subject} — Lecture Notes\n")
        f.write(f"**Date:** {datetime.now().strftime('%B %d, %Y')}  \n")
        f.write(f"**Generated by:** Virtual Avatar — Meeting Notes Taker (Gemini Vision)\n\n")
        f.write("---\n\n")
    print(f"📁 Notes file: {path}")
    return path

# ══════════════════════════════════════════════════════
#  GEMINI CLIENT + MODEL CASCADE
# ══════════════════════════════════════════════════════
ai_clients = [genai.Client(api_key=k) for k in GEMINI_API_KEYS]
ai_client = ai_clients[0] if ai_clients else None  # kept for any code path still expecting "the" client

NOTES_MODELS = [
    "gemini-2.5-flash",       # primary   — best quality, 65k output
    "gemini-2.5-flash-lite",  # fallback 1 — faster, still good
    "gemini-2.0-flash",       # fallback 2 — reliable fallback
]
notes_key_index   = 0
notes_model_index = 0

# ══════════════════════════════════════════════════════
#  MATH NOTES PROMPT
#  Gemini receives the full video (screen + audio) and this prompt.
#  We ask it to be exhaustive because math notes need every formula.
# ══════════════════════════════════════════════════════
def build_notes_prompt(subject: str, chunk_num: int) -> str:
    listener_name = _CFG.get("student_name", "the listener")
    return f"""You are an expert note-taker reviewing a recorded segment (Part {chunk_num}) of an
online meeting, class, or call that **{listener_name}** is attending live.
The topic/subject is: **{subject}**

{listener_name} cannot type notes while listening — they are focused on following along —
so your job is to produce the comprehensive notes they would have written themselves,
covering everything said and shown in this segment.

You have the full recording — analyze BOTH what is visible on screen AND what is being said
(presentation slides, shared documents, code, whiteboards, speech from any participant).

Write exhaustive, well-structured Markdown notes. For EVERY topic, decision, or discussion
point covered in this segment:

1. **Topic / Discussion Point** as a `##` heading
2. **Overview** — brief 2–3 sentence summary of what was discussed and why it matters
3. **Key Points & Definitions** — capture every important term, decision, action item, or idea raised. Be precise.
4. **Detailed Explanation** — explain it fully enough that someone who missed this segment entirely understands exactly what was covered
5. **Formulas, Code, Data & Structured Content** — if applicable:
   - Write ALL math using LaTeX: inline $formula$ or display $$formula$$
   - Write ALL code in fenced code blocks with the correct language tag
   - Capture any numbers, figures, or structured rules mentioned, exactly as stated
6. **Examples / Demonstrations Shown** — reproduce any example, demo, or walkthrough shown on screen, in full
7. **Action Items / Decisions / Follow-ups** — anything that was decided, assigned, or needs follow-up (skip this section if none occurred)
8. **Key Takeaways** — bullet-point the most important things emphasized in this segment
9. **Quick Review Q&A** — write 3–5 short questions with answers, useful for self-testing or quick review later (skip if not relevant for this kind of meeting)

Rules:
- Be exhaustive — someone who missed this segment entirely should be able to fully understand it from your notes alone
- Never truncate or summarize away detail — write the full, complete notes for everything covered
- If the segment covers multiple topics, repeat the full structure above for each one
- If this is a continuation of an earlier topic, still write fully self-contained notes
- Use LaTeX for all mathematical expressions — never write math as plain text
- Use proper Markdown: headings, bold, bullet points, numbered lists, code blocks, tables where useful
- Do NOT add disclaimers, meta-commentary, or notes about what you couldn't see — just write the best notes you can from the available content
"""

# ══════════════════════════════════════════════════════
#  GEMINI — GENERATE NOTES FROM VIDEO CHUNK
# ══════════════════════════════════════════════════════
def generate_chunk_notes(video_file_path: str, chunk_num: int, subject: str):
    global notes_key_index, notes_model_index

    timestamp = datetime.now().strftime("%I:%M %p")
    file_size_mb = os.path.getsize(video_file_path) / (1024 * 1024)
    print(f"\n[AI Scribe] ☁️  Uploading Chunk {chunk_num} ({file_size_mb:.1f} MB) at {timestamp}...")

    # Uploaded files are scoped to the client/key that uploaded them — if we
    # rotate to a different key partway through, the file must be re-uploaded
    # (and re-processed) under the new client before it can be used there.
    uploaded_file = None
    uploaded_file_client = None

    def _upload_and_wait(client) -> bool:
        """Upload video_file_path under `client` and wait for it to become
        ACTIVE. Returns True on success; leaves uploaded_file/_client set."""
        nonlocal uploaded_file, uploaded_file_client
        f = client.files.upload(file=video_file_path)
        if f is None or not f.name:
            print(f"[AI Scribe] ❌ Failed to upload chunk {chunk_num}")
            return False
        uploaded_file, uploaded_file_client = f, client

        print(f"[AI Scribe] ⏳ Waiting for Gemini to process video...")
        max_wait, waited = 120, 0
        while waited < max_wait:
            file_info = client.files.get(name=f.name)
            state = str(getattr(file_info, 'state', '')).upper()
            if 'ACTIVE' in state or 'PROCESSED' in state:
                return True
            if 'FAILED' in state:
                print(f"[AI Scribe] ❌ File processing failed for chunk {chunk_num}")
                return False
            time.sleep(5)
            waited += 5
        print(f"[AI Scribe] ⚠️  Timed out waiting for file processing — trying anyway.")
        return True

    try:
        if not _upload_and_wait(ai_clients[notes_key_index]):
            return

        prompt = build_notes_prompt(subject, chunk_num)

        response = None
        # Try every (key, model) combination. For quota errors, retry up to
        # 2x with backoff on the SAME model first (transient quota blips);
        # if still failing, step to the next model; once all models on this
        # key are exhausted, rotate to the next key and re-upload there.
        total_models = len(GEMINI_API_KEYS) * len(NOTES_MODELS)
        for _ in range(total_models):
            client = ai_clients[notes_key_index]
            model  = NOTES_MODELS[notes_model_index]
            print(f"[AI Scribe] 🧠 Analyzing chunk {chunk_num} with {model} "
                  f"(key #{notes_key_index + 1}/{len(GEMINI_API_KEYS)})...")

            stepped_down = False
            for attempt in range(3):  # up to 3 attempts per model
                try:
                    response = client.models.generate_content(
                        model=model,
                        contents=[uploaded_file, prompt],
                        config={
                            "max_output_tokens": 65536,
                            "temperature": 0.4,
                        }
                    )
                    break  # success
                except Exception as e:
                    err = str(e)
                    if "429" in err:
                        wait = 30 * (attempt + 1)
                        print(f"⚠️  [{model}] quota hit — waiting {wait}s before retry ({attempt+1}/3)...")
                        time.sleep(wait)
                    elif "not supported" in err.lower() or "video" in err.lower():
                        print(f"⚠️  [{model}] video not supported — trying next model...")
                        stepped_down = True
                        break  # step down immediately, no point retrying
                    else:
                        print(f"❌ [AI Scribe] Gemini error ({model}) chunk {chunk_num}: {e}")
                        response = None
                        stepped_down = None  # signal: hard failure, stop entirely
                        break
            if response is not None:
                break  # got a response, stop trying

            if stepped_down is None:
                break  # non-quota, non-support error — give up on this chunk

            # Exhausted this model's retries (or it doesn't support video) —
            # step to the next model, rotating keys once we run out of models.
            notes_model_index += 1
            if notes_model_index >= len(NOTES_MODELS):
                notes_model_index = 0
                notes_key_index = (notes_key_index + 1) % len(GEMINI_API_KEYS)
                print(f"⚠️  All models exhausted on previous key — switching to Gemini key "
                      f"#{notes_key_index + 1}/{len(GEMINI_API_KEYS)}...")
                if not _upload_and_wait(ai_clients[notes_key_index]):
                    response = None
                    break

        if response is None:
            print(f"❌ [AI Scribe] All keys/models failed for chunk {chunk_num}. Skipping.")
            return

        # Append notes to file
        notes_file = NOTES_FILE
        if notes_file is None:
            raise RuntimeError("Notes file not initialized")

        with FILE_LOCK:
            with open(notes_file, "a", encoding="utf-8") as f:
                f.write(f"\n---\n\n## 🕒 Part {chunk_num} — {timestamp}\n\n")
                f.write((response.text or "").strip() + "\n\n")

        print(f"✅ [AI Scribe] Chunk {chunk_num} notes saved!")

    except Exception as e:
        print(f"❌ [AI Scribe] Unexpected error on chunk {chunk_num}: {e}")
    finally:
        # Always clean up uploaded file and local temp file
        try:
            if uploaded_file and uploaded_file_client and uploaded_file.name:
                uploaded_file_client.files.delete(name=uploaded_file.name)
        except Exception:
            pass
        if os.path.exists(video_file_path):
            os.remove(video_file_path)

# ══════════════════════════════════════════════════════
#  SCREEN RECORDER DETECTION
# ══════════════════════════════════════════════════════
def _probe_wf_recorder() -> bool:
    """Return True if wf-recorder actually works on this compositor.
    GNOME/KDE Wayland use Mutter/KWin which don't support wlr-screencopy,
    so wf-recorder exits immediately with an error.

    NOTE: previously this slept a fixed 1.5s then sent SIGINT and trusted
    whatever stderr happened to be captured by that point. If the
    compositor's rejection message landed a moment later than 1.5s, the
    probe read empty output and wrongly reported success. Now we poll for
    up to 4s for the process to exit on its own (the rejection is
    near-instant when it happens) and only fall back to the SIGINT timeout
    path if it's still running, meaning it's actually recording fine."""
    probe_file = "/tmp/wf_probe_test.mp4"
    try:
        proc = subprocess.Popen(
            ["wf-recorder", "-f", probe_file, "--codec", "libx264"],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.PIPE
        )
        # Poll briefly for early failure instead of trusting a fixed sleep —
        # an unsupported compositor rejects almost immediately, but timing
        # varies slightly, so give it real room to fail before assuming success.
        for _ in range(8):  # up to 4s
            if proc.poll() is not None:
                break
            time.sleep(0.5)

        if proc.poll() is None:
            # Still running after 4s = it's actually recording, not erroring out
            proc.send_signal(signal.SIGINT)
        try:
            _, stderr = proc.communicate(timeout=5)
        except subprocess.TimeoutExpired:
            proc.kill()
            _, stderr = proc.communicate()
        stderr_text = stderr.decode(errors="replace").lower()
        if "doesn't support" in stderr_text or "not supported" in stderr_text or "failed" in stderr_text:
            return False
        if proc.returncode not in (0, None) and proc.returncode != -signal.SIGINT:
            # Non-zero, non-SIGINT exit with no recognizable error string —
            # treat as failure rather than assuming success on an empty stderr.
            return False
        return True
    except Exception:
        return False
    finally:
        if os.path.exists(probe_file):
            os.remove(probe_file)


def detect_recorder() -> str:
    """Returns 'wf-recorder' (Wayland/wlroots) or 'ffmpeg' (X11/GNOME) or raises."""
    wayland = os.environ.get("WAYLAND_DISPLAY") or os.environ.get("XDG_SESSION_TYPE", "").lower() == "wayland"

    # GNOME's compositor (Mutter) NEVER supports wlr-screencopy-unstable-v1 —
    # that protocol is a wlroots-only thing (Sway, Hyprland, etc). Running the
    # timing-based probe here is actively harmful: it sends SIGINT after a
    # fixed 1.5s, and if Mutter's rejection message lands on stderr a moment
    # later than that, the probe reads empty/partial output, finds no error
    # string, and wrongly reports success — which is exactly what happened:
    # the banner said "using wf-recorder" while every real chunk died
    # instantly with "compositor doesn't support wlr-screencopy-unstable-v1".
    # Skip the gamble entirely and go straight to ffmpeg on GNOME.
    desktop = os.environ.get("XDG_CURRENT_DESKTOP", "").lower()
    if wayland and "gnome" in desktop:
        print("🖥️  GNOME/Mutter detected — wlr-screencopy is never supported here, skipping wf-recorder probe.")
    elif wayland:
        result = subprocess.run(["which", "wf-recorder"], capture_output=True)
        if result.returncode == 0:
            print("🖥️  Wayland detected — probing compositor compatibility...")
            if _probe_wf_recorder():
                print("🖥️  Display: Wayland (wlroots) → using wf-recorder")
                return "wf-recorder"
            else:
                print("⚠️  Compositor doesn't support wlr-screencopy (GNOME/KDE Mutter/KWin).")
                print("   Falling back to ffmpeg x11grab via XWayland...")
        else:
            print("⚠️  Wayland detected but wf-recorder not found — trying ffmpeg fallback...")

    # X11 or Wayland with incompatible compositor → try ffmpeg
    result = subprocess.run(["which", "ffmpeg"], capture_output=True)
    if result.returncode == 0:
        display = os.environ.get("DISPLAY", "")
        if display:
            print(f"🖥️  Display: {display} → using ffmpeg x11grab")
        else:
            print("🖥️  Display: X11 → using ffmpeg x11grab")
        return "ffmpeg"

    print("❌ CRITICAL: No screen recorder found!")
    print("   Install one of:")
    print("   sudo dnf install wf-recorder   (Wayland/wlroots — Sway, Hyprland)")
    print("   sudo dnf install ffmpeg         (X11 / GNOME Wayland via XWayland)")
    sys.exit(1)


def get_audio_monitor_source() -> str:
    """Find the best PipeWire/PulseAudio monitor source for desktop audio.

    Strategy:
      1. Use pactl to find the *default* sink, then return its .monitor source.
         This ensures we capture whatever the user is actually hearing.
      2. Fall back to any non-HDMI monitor source.
      3. Last resort: 'default'.
    """
    try:
        # Get default sink name
        default_sink = subprocess.check_output(
            ["pactl", "get-default-sink"], text=True, stderr=subprocess.DEVNULL
        ).strip()
        if default_sink:
            monitor = f"{default_sink}.monitor"
            print(f"🎵 Audio source: {monitor} (default sink monitor)")
            return monitor
    except Exception:
        pass

    try:
        out = subprocess.check_output(["pactl", "list", "sources", "short"],
                                      text=True, stderr=subprocess.DEVNULL)
        # Prefer non-HDMI monitor sources (analogue/USB headphones/speakers)
        for line in out.splitlines():
            if "monitor" in line.lower() and "hdmi" not in line.lower() and "virtual" not in line.lower():
                src = line.split()[1]
                print(f"🎵 Audio source: {src} (desktop monitor)")
                return src
        # Any monitor source as last resort
        for line in out.splitlines():
            if "monitor" in line.lower() and "virtual" not in line.lower():
                src = line.split()[1]
                print(f"🎵 Audio source: {src} (fallback monitor)")
                return src
    except Exception:
        pass

    print("⚠️  Could not auto-detect audio source — using default")
    return "default"


def start_recorder(recorder: str, output_file: str, audio_src: str) -> subprocess.Popen:
    """Start screen+audio recording. Returns the subprocess."""
    if recorder == "wf-recorder":
        # wf-recorder: -a = include audio (PipeWire/PulseAudio device)
        # --audio-codec is NOT a valid wf-recorder flag — omit it
        cmd = [
            "wf-recorder",
            "-a", audio_src,          # capture desktop audio
            "-f", output_file,        # output file
            "--codec", "libx264",     # video codec
            "-p", f"crf={VIDEO_CRF}", # quality
        ]
    else:
        # ffmpeg X11 grab (works on GNOME Wayland via XWayland)
        display = os.environ.get("DISPLAY", ":0.0")
        cmd = [
            "ffmpeg", "-y",
            "-f", "x11grab",
            "-framerate", str(VIDEO_FPS),
            "-i", display,
            "-f", "pulse",
            "-i", audio_src,
            "-c:v", "libx264",
            "-preset", "ultrafast",
            "-crf", str(VIDEO_CRF),
            "-c:a", "aac",
            output_file  # mkv preferred — no trailer needed, safe on Ctrl+C
        ]

    proc = subprocess.Popen(
        cmd,
        stdout=subprocess.DEVNULL,
        stderr=open("/tmp/recorder_stderr.log", "w"),  # log errors for debugging
        start_new_session=True  # isolate from terminal Ctrl+C so we control shutdown
    )
    return proc


def stop_recorder(proc: subprocess.Popen, recorder: str):
    """Gracefully stop the recorder so it finalizes the file."""
    if proc.poll() is not None:
        return  # already stopped
    try:
        proc.send_signal(signal.SIGINT)
        proc.wait(timeout=10)
    except subprocess.TimeoutExpired:
        proc.kill()
        proc.wait()

# ══════════════════════════════════════════════════════
#  MAIN
# ══════════════════════════════════════════════════════
def main():
    global NOTES_FILE

    print("╔══════════════════════════════════════════════════╗")
    print("║      📝  YouTube Lecture Notes Taker            ║")
    print("╚══════════════════════════════════════════════════╝\n")

    if not GEMINI_API_KEYS:
        print("❌ No Gemini API key found in config.json")
        print('   Add at least one key to config.json: { "gemini_keys": ["your_key"] }')
        sys.exit(1)

    # ── Session info: CLI args (from UI) take priority over prompts ──
    default_subject = _CFG.get("last_yt_subject", "Meeting")
    default_dir = _CFG.get("last_notes_dir",
                            os.path.expanduser("~/Documents/Meeting_Notes"))

    if _cli_args.subject or _cli_args.notes_dir or _cli_args.chunk:
        # Launched from the UI — never call input(), it would hang forever
        # since the spawned process has no attached stdin.
        subject     = _cli_args.subject or default_subject
        notes_dir   = os.path.expanduser(_cli_args.notes_dir or default_dir)
        chunk_minutes = _cli_args.chunk or CHUNK_MINUTES
        print(f"📚 Subject     : {subject}  (from launch args)")
        print(f"📁 Notes folder: {notes_dir}  (from launch args)")
        print(f"⏱️  Chunk      : {chunk_minutes} min  (from launch args)")
    else:
        subject = input(f"📚 Subject [{default_subject}]: ").strip() or default_subject

        notes_dir = input(f"📁 Notes folder [{default_dir}]: ").strip() or default_dir
        notes_dir = os.path.expanduser(notes_dir)

        chunk_min_input = input(f"⏱️  Chunk length in minutes [{CHUNK_MINUTES}]: ").strip()
        # Strip non-digit suffix so "15min" or "15m" works
        chunk_min_digits = "".join(c for c in chunk_min_input if c.isdigit())
        chunk_minutes = int(chunk_min_digits) if chunk_min_digits else CHUNK_MINUTES

    # Save prefs for next run
    _CFG["last_yt_subject"] = subject
    _CFG["last_notes_dir"]  = notes_dir
    with open(_CONFIG_FILE, "w") as f:
        json.dump(_CFG, f, indent=2)

    # Initialize notes file
    NOTES_FILE = init_notes_file(subject, notes_dir)

    # Detect recorder and audio source
    recorder   = detect_recorder()
    audio_src  = get_audio_monitor_source()

    print(f"\n⏱️  Chunk length   : {chunk_minutes} minutes")
    print(f"🧠 AI model       : {NOTES_MODELS[notes_model_index]}")
    print(f"📄 Notes file     : {NOTES_FILE}")
    print(f"\n▶️  Starting in 3 seconds... Open your YouTube video now!")
    print("   Press Ctrl+C at any time to stop and save final notes.\n")
    time.sleep(3)

    # ── Main recording loop ──────────────────────────
    chunk_num     = 1
    running       = True
    current_proc  = None

    notes_threads: list[threading.Thread] = []

    def run_loop():
        nonlocal chunk_num, current_proc, running

        while running:
            chunk_file = f"/tmp/yt_chunk_{chunk_num}_{uuid.uuid4().hex}.mkv"
            print(f"\n🔴 Recording chunk {chunk_num}... (next notes in {chunk_minutes} min)")

            current_proc = start_recorder(recorder, chunk_file, audio_src)

            # Wait for chunk duration OR until Ctrl+C sets running=False
            deadline = time.time() + (chunk_minutes * 60)
            while running and time.time() < deadline:
                # Check if recorder died unexpectedly
                if current_proc.poll() is not None:
                    print(f"⚠️  Recorder stopped unexpectedly on chunk {chunk_num}. Check /tmp/recorder_stderr.log for details. Restarting...")
                    break
                time.sleep(2)

            # Stop recorder cleanly so it can finalize the file
            stop_recorder(current_proc, recorder)
            current_proc = None

            # For mid-session chunks require 50KB (filters out crash artifacts).
            # For the final chunk (after Ctrl+C) accept anything > 1KB — always process it.
            is_final_chunk = not running
            min_size = 1_000 if is_final_chunk else 50_000
            if os.path.exists(chunk_file) and os.path.getsize(chunk_file) > min_size:
                t = threading.Thread(
                    target=generate_chunk_notes,
                    args=(chunk_file, chunk_num, subject),
                    daemon=False  # non-daemon: process must not die before notes are saved
                )
                t.start()
                notes_threads.append(t)
            else:
                print(f"⚠️  Chunk {chunk_num} too small — skipping.")
                if os.path.exists(chunk_file):
                    os.remove(chunk_file)

            chunk_num += 1

    # ── Run in main thread, catch Ctrl+C ───────────
    loop_thread = threading.Thread(target=run_loop, daemon=True)
    loop_thread.start()

    try:
        loop_thread.join()
    except KeyboardInterrupt:
        print("\n\n🛑 Stopping... finishing current chunk.")
        running = False
        # Do NOT call stop_recorder here — loop_thread owns the recorder and
        # will stop it + process the final chunk on its own now that running=False.

        # Wait for loop_thread to finish stopping the recorder and spawning the
        # final notes thread (should be fast — just a graceful ffmpeg shutdown)
        loop_thread.join(timeout=30)

        # Wait for every notes thread to finish — guaranteed, not just a timeout poll
        pending = [t for t in notes_threads if t.is_alive()]
        if pending:
            print(f"⏳ Waiting for AI to finish generating notes ({len(pending)} chunk(s) in progress)...")
            for t in pending:
                try:
                    t.join(timeout=180)  # up to 3 min per thread
                except KeyboardInterrupt:
                    print("   (Force exit — some notes may not be saved)")
                    break

        print(f"\n✅ Done! Notes saved at:\n   {NOTES_FILE}")
        sys.exit(0)


if __name__ == "__main__":
    main()
